# Generated by Django 3.1.5 on 2021-02-05 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=100)),
                ('kurs', models.IntegerField()),
                ('forma', models.CharField(choices=[('дневная', 'дневная'), ('заочная', 'заочная')], default='дневная', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=100)),
                ('imya', models.CharField(max_length=100)),
                ('otchestvo', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('data_rozhd', models.DateField(default=datetime.date.today)),
                ('sex', models.CharField(choices=[('м', 'муж'), ('ж', 'жен')], default='м', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Specialnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviatura', models.CharField(max_length=100)),
                ('polnoe_nazv', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spisok_stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=100)),
                ('imya', models.CharField(max_length=100)),
                ('otchestvo', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('м', 'муж'), ('ж', 'жен')], default='м', max_length=1)),
                ('vpo', models.BooleanField()),
                ('sirota', models.BooleanField()),
                ('invalid', models.BooleanField()),
                ('ato', models.BooleanField()),
                ('chernobil', models.BooleanField()),
                ('maloobespech', models.BooleanField()),
                ('budget', models.BooleanField()),
                ('data_rozhdeniya', models.DateField(default=datetime.date.today)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('n_tel', models.CharField(max_length=13)),
                ('inn', models.CharField(max_length=100)),
                ('pasport', models.CharField(max_length=100)),
                ('id_stan', models.CharField(max_length=100)),
                ('n_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Predmety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv_predmeta', models.CharField(max_length=100)),
                ('specialnost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.specialnost')),
            ],
        ),
        migrations.CreateModel(
            name='Itog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsenka', models.IntegerField()),
                ('n_predmeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.predmety')),
                ('n_prepod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.prepod')),
                ('n_stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.spisok_stud')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='n_specialnosty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.specialnost'),
        ),
    ]
