# Generated by Django 3.1.5 on 2021-02-01 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210201_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepod',
            name='data_rozhd',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='spisok_stud',
            name='data_rozhdeniya',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
