# Generated by Django 3.1.5 on 2021-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210205_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialnost',
            name='abbreviatura',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
