# Generated by Django 3.1.5 on 2021-02-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210205_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='forma',
            field=models.CharField(choices=[('денна', 'денна'), ('заочна', 'заочна')], default='денна', max_length=7),
        ),
    ]
