# Generated by Django 3.1.5 on 2021-02-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210205_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisok_stud',
            name='sex',
            field=models.CharField(choices=[('м', 'чол'), ('ж', 'жін')], default='м', max_length=1),
        ),
    ]
