# Generated by Django 3.1.6 on 2021-02-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210205_2030'),
        ('register', '0003_auto_20210201_1614'),
    ]

    operations = [
    ]
