# Generated by Django 3.1.6 on 2021-02-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_merge_20210205_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='n_group',
        ),
        migrations.RemoveField(
            model_name='itog',
            name='n_itoga',
        ),
        migrations.RemoveField(
            model_name='predmety',
            name='n_predmeta',
        ),
        migrations.RemoveField(
            model_name='prepod',
            name='n_prepod',
        ),
        migrations.AlterField(
            model_name='itog',
            name='n_predmeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.predmety'),
        ),
        migrations.AlterField(
            model_name='itog',
            name='n_prepod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.prepod'),
        ),
        migrations.AlterField(
            model_name='itog',
            name='n_stud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.spisok_stud'),
        ),
        migrations.AlterField(
            model_name='specialnost',
            name='n_specialnosty',
            field=models.CharField(max_length=5),
        ),
    ]
