# Generated by Django 3.1.5 on 2021-02-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210206_2101'),
        ('register', '0007_auto_20210205_2256'),
    ]

    operations = [
    ]
