# Generated by Django 3.1.6 on 2021-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20210328_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spisok_stud',
            name='id_stan',
            field=models.CharField(choices=[('н', 'Навчається'), ('в', 'Відраховано'), ('з', 'Завершив навчання')], default='ч', max_length=1),
        ),
    ]
