# Generated by Django 3.1.6 on 2021-03-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20210328_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='forma',
            field=models.CharField(choices=[('Денна', 'Денна'), ('Заочна', 'Заочна')], default='Денна', max_length=7),
        ),
        migrations.AlterField(
            model_name='prepod',
            name='sex',
            field=models.CharField(choices=[('Чол', 'Чол'), ('Жін', 'Жін')], default='Чол', max_length=3),
        ),
        migrations.AlterField(
            model_name='spisok_stud',
            name='id_stan',
            field=models.CharField(choices=[('Навчається', 'Навчається'), ('Відраховано', 'Відраховано'), ('Завершив навчання', 'Завершив навчання')], default='Навчається', max_length=20),
        ),
        migrations.AlterField(
            model_name='spisok_stud',
            name='sex',
            field=models.CharField(choices=[('Чол', 'Чол'), ('Жін', 'Жін')], default='Чол', max_length=3),
        ),
    ]
