# Generated by Django 3.1.6 on 2021-04-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20210410_0939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='predmety',
            unique_together=set(),
        ),
    ]
