# Generated by Django 3.1.6 on 2021-04-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20210410_0957'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='predmety',
            index_together={('nazv_predmeta', 'specialnost')},
        ),
    ]
