# Generated by Django 3.1.6 on 2021-04-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20210413_1056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='predmety',
            unique_together={('nazv_predmeta', 'specialnost')},
        ),
        migrations.AlterIndexTogether(
            name='predmety',
            index_together=set(),
        ),
    ]
