# Generated by Django 3.1.6 on 2021-04-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20210413_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='predmety',
            unique_together=set(),
        ),
    ]
